image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK"

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

.set_env_variables: &set_env_variables
  - PROJECT_VERSION=$(xmllint --xpath '/*[local-name()="project"]/*[local-name()="version"]/text()' pom.xml)

stages:
  - build
  - test
  - publish

cache:
  key: "$CI_COMMIT_SHA"
  paths:
    - target/

###################
### Stage build ###
###################

.compile:
  before_script: *set_env_variables
  script:
    - echo "Compiling version $PROJECT_VERSION"
    - mvn $MAVEN_CLI_OPTS -U clean install
  stage: build

compile:
  extends: .compile

compile:openjdk11:
  extends: .compile
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

##################
### Stage test ###
##################

.verify:
  dependencies:
    - compile
    - compile:openjdk11
  script: mvn $MAVEN_CLI_OPTS verify
  stage: test

verify:
  extends: .verify

verify:openjdk11:
  extends: .verify
  image: "$BUILD_IMAGE_ANSIBLE_MAVEN_JDK11"
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-11-openjdk-amd64"

#####################
### Stage publish ###
#####################

.publish:
  before_script: *set_env_variables
  dependencies:
    - verify
  except:
    variables:
      - $NO_PUBLISH
  stage: publish

publish_snapshot:
  extends: .publish
  only:
    - master
  script:
    - if [[ ! "$PROJECT_VERSION" =~ .*SNAPSHOT ]]; then exit 0; fi
    - mvn $MAVEN_CLI_OPTS -T 4 deploy --settings settings.xml

publish_release:
  extends: .publish
  only:
    - tags
  script:
    - if [[ "$PROJECT_VERSION" =~ .*SNAPSHOT ]]; then exit 0; fi
    - mvn $MAVEN_CLI_OPTS -fn -T 4 deploy --settings settings.xml
